name: Scrape and Publish

on:
  workflow_dispatch:
  schedule:
    - cron: "37 2 * * *" # Run every day at 2:37 am

jobs:
  scrape:
    name: Scrape and Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: Install project
        run: uv sync
      - name: Fetch the current .duckdb file from the data_v1_latest branch
        run: uv run python -m alaska_legislative_data fetch
      - name: Ingest new data into the .duckdb file
        run: uv run python -m alaska_legislative_data ingest
      - name: Export to the /export directory
        run: uv run python -m alaska_legislative_data export
      - name: Push export/ to the data_v1_latest
        run: |
          git config --global user.email "nicholas.b.crews@gmail.com"
          git config --global user.name "Nick Crews"
          uv run python -m alaska_legislative_data push