name: Scrape and Publish

on:
  workflow_dispatch:
  schedule:
    - cron: "37 2 * * *" # Run every day at 2:37 am

permissions:
  contents: write

jobs:
  scrape:
    name: Scrape and Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install project
        run: uv sync

      - name: Ingest new data into motherduck
        env:
          motherduck_token: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: uv run python -m alaska_legislative_data ingest --db="md:ak_leg"

      - name: Export to the /export directory
        env:
          motherduck_token: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: uv run python -m alaska_legislative_data export --db="md:ak_leg"

      - name: Publish the /export directory to a GH release
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./release.sh export